// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZjDMOxRlpErlsRgU_mPP1fJ2EQyYefnQ',
    appId: '1:489864260131:web:3d10a0c3eb87efbc745f96',
    messagingSenderId: '489864260131',
    projectId: 'smart-trolley-cdd7b',
    authDomain: 'smart-trolley-cdd7b.firebaseapp.com',
    databaseURL:
        'https://smart-trolley-cdd7b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-trolley-cdd7b.appspot.com',
    measurementId: 'G-JC0NEX8EH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD22keXS8atF7HXEi1cj_hhwubBgDPv0rg',
    appId: '1:489864260131:android:69a29f7406e1d32f745f96',
    messagingSenderId: '489864260131',
    projectId: 'smart-trolley-cdd7b',
    databaseURL:
        'https://smart-trolley-cdd7b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-trolley-cdd7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs0XtMqrMB9NoC0tFhf8v3tOYYks2KVBo',
    appId: '1:489864260131:ios:37b38acc7fc283d2745f96',
    messagingSenderId: '489864260131',
    projectId: 'smart-trolley-cdd7b',
    databaseURL:
        'https://smart-trolley-cdd7b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-trolley-cdd7b.appspot.com',
    iosClientId:
        '489864260131-qridrm47cf86d5haiso0lu36c3h3lgbn.apps.googleusercontent.com',
    iosBundleId: 'com.autobonics.hydropodHydroponics',
  );
}
